
version: "3"

services:
    
  nifi_4:
    build: ./nifi
    image: apache/nifi:latest
    restart: always
    ports:
      - 8443:8443
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
    volumes:
      - ./data:/tmp/data
      #- ./nifi:/opt/nifi/conf/templates/ejemplos/
      #- ./nifi:/opt/nifi/nifi-current/conf/ejemplos

#dircetorio donde esta el  
#/opt/nifi/nifi-current/conf
    
  nifi-registry:
    image: apache/nifi-registry:latest
    container_name: nifiregistry
    restart: always
    ports:
      - 18080:18080

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017    
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/


#notebbok